crudexample/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('employee/', include('employee.urls',  namespace='employee' )),
    path('', RedirectView.as_view(url='accounts/login/', permanent=True)),  # Redirect root URL to login
    path('transaction/', include('transactions.urls',  namespace='transactions')),
    path('files/', include('files.urls',  namespace='files' )),
    path('photos/', include('photo_gallery.urls', namespace='photo_gallery')),
    path('product/', include('product.urls',  namespace='product' )),
    path('sales/', include('sales.urls',  namespace='sales' )),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

files/urls.py
from django.urls import path
from . import views
from .views import FileListView

app_name = 'files'

urlpatterns = [
    path('', views.directory_view, name='home'),
    path('directory/<int:dir_id>/', views.directory_view, name='directory_view'),
    path('add_directory/', views.add_directory, name='add_directory'),
    path('file_list/', FileListView.as_view(), name='file_list'),  # Add this line
    path('delete_directory/<int:pk>/', views.delete_directory, name='delete_directory'),
    path('add_file/', views.add_file, name='add_file'),
    path('delete_file/<int:pk>/', views.delete_file, name='delete_file'),
    path('files/listing/', views.file_listing, name='file_listing'),   
    path('edit_file/<int:file_id>/', views.edit_file, name='edit_file'),
    path('add-pdf-password/', views.add_pdf_password_view, name='add_pdf_password'),
    path('add-watermark/', views.add_watermark_view, name='add_watermark'),
    path('add-texture/', views.add_texture_view, name='add_texture'),
    path('download-pdf/<str:filename>/', views.download_pdf_view, name='download_pdf'),
    
    
]

files/models.py
from django.db import models
from django.utils import timezone

class Directory(models.Model):
    name = models.CharField(max_length=255)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='subdirectories')

    def __str__(self):
        return self.name

    @property
    def get_ancestors(self):
        ancestors = []
        current = self.parent
        while current:
            ancestors.insert(0, current)
            current = current.parent
        return ancestors

class File(models.Model):
    name = models.CharField(max_length=255)
    file = models.FileField(upload_to='uploads/', null=True, blank=True)
    url = models.URLField(null=True, blank=True)
    directory = models.ForeignKey(Directory, on_delete=models.CASCADE, related_name='files')
    owner = models.CharField(max_length=255)
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name

    @property
    def link(self):
        return self.url if self.url else self.file.url if self.file else None
        

files/forms.py
from django import forms
from .models import Directory, File

class DirectoryForm(forms.ModelForm):
    class Meta:
        model = Directory
        fields = ['name', 'parent']
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Enter directory name', 'class': 'form-control'}),
            'parent': forms.Select(attrs={'class': 'form-control'}),
        }

class FileForm(forms.ModelForm):
    class Meta:
        model = File
        fields = ['name', 'owner', 'file', 'url', 'directory']
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Enter file / URL name', 'class': 'form-control'}),
            'owner': forms.TextInput(attrs={'placeholder': 'Owner of the file', 'class': 'form-control'}),
            'file': forms.ClearableFileInput(attrs={'placeholder': 'Select a file', 'class': 'form-control-file'}),
            'url': forms.URLInput(attrs={'placeholder': 'Enter file URL', 'class': 'form-control'}),
            'directory': forms.Select(attrs={'class': 'form-control'}),
        }


class PDFPasswordForm(forms.Form):
    pdf_file = forms.FileField(label="Upload PDF")
    password = forms.CharField(widget=forms.PasswordInput, label="Password")
    


class PDFWatermarkForm(forms.Form):
    pdf_file = forms.FileField(label="Select PDF file")
    watermark_text = forms.CharField(label="Watermark Text", max_length=100)
    


class PDFTextureForm(forms.Form):
    pdf_file = forms.FileField(label="PDF File")
    texture_image = forms.ImageField(label="Texture Image")
    opacity = forms.FloatField(label="Opacity", initial=0.3, min_value=0, max_value=1)

files/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Directory, File
from .forms import DirectoryForm, FileForm
from django.contrib import messages
from django_filters.views import FilterView
from .filters import FileFilter
from django.views.decorators.csrf import csrf_exempt

import os
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from PyPDF2 import PdfReader, PdfWriter
from .forms import PDFPasswordForm

from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
from .forms import PDFWatermarkForm

import tempfile
from PIL import Image, ImageEnhance
import fitz  # PyMuPDF
from .forms import PDFTextureForm


def directory_view(request, dir_id=None):
    directory = None
    if dir_id:
        directory = get_object_or_404(Directory, id=dir_id)
        subdirectories = Directory.objects.filter(parent=directory)
        files = File.objects.filter(directory=directory)
        parent_id = directory.pk  # Parent directory ID for new subdirectories
    else:
        subdirectories = Directory.objects.filter(parent=None)
        files = File.objects.filter(directory=None)
        parent_id = None

    context = {
        'current_directory': directory if dir_id else None,
        'subdirectories': subdirectories,
        'files': files,
        'dir_form': DirectoryForm(),
        'file_form': FileForm(),
        'parent_id': parent_id,
        'current_directory_id': directory.pk if directory else None,
    }
    return render(request, 'files/file.html', context)

def add_directory(request):
    if request.method == 'POST':
        form = DirectoryForm(request.POST)

        if form.is_valid():
            directory = form.save(commit=False)
            parent_id = request.POST.get('parent')

            # Debug print statements
            print("Parent ID from form:", parent_id)
            print("Form is valid. Directory name:", directory.name)

            # Determine if this is a root directory creation
            if not parent_id or parent_id in ['0', 'None', '', None]:  # Handle root directory creation
                directory.parent = None
            else:
                # Attempt to retrieve parent directory
                parent_directory = Directory.objects.filter(pk=parent_id).first()
                if parent_directory:
                    directory.parent = parent_directory
                else:
                    print("No valid parent found; creating as root directory.")
                    directory.parent = None  # Default to root if parent not found

            # Debug: Print the parent directory
            print("Resolved Parent Directory:", directory.parent)

            directory.save()

            # Redirect back to the appropriate view
            if directory.parent:
                return redirect('files:directory_view', dir_id=directory.parent.pk)
            return redirect('files:home')
        else:
            # Print form errors to debug why it's not valid
            print("Form is not valid. Errors:", form.errors)

            # Attempt to create a root directory if form is invalid
            # due to parent field issues
            if 'parent' in form.errors:
                print("Creating root directory as fallback.")
                directory = Directory(name=request.POST.get('name'), parent=None)
                directory.save()
                return redirect('files:home')

    else:
        # Debug: Log if the request method is not POST
        print("Request method is not POST.")

    return redirect('files:home')

def add_file(request):
    if request.method == 'POST':
        form = FileForm(request.POST, request.FILES)
        if form.is_valid():
            file = form.save(commit=False)
            # Ensure either file or URL is provided
            if not (file.file or file.url):
                form.add_error(None, "Either upload a file or provide a URL.")
            else:
                file.save()
                return redirect('files:home')
                
    return redirect('files:home')
    


def delete_directory(request, pk):
    directory = get_object_or_404(Directory, pk=pk)
    directory.delete()
    return redirect('files:home')

def delete_file(request, pk):
    file = get_object_or_404(File, pk=pk)
    file.delete()
    return redirect('files:file_listing')


class FileListView(FilterView):
    model = File
    template_name = 'files/file_list.html'
    context_object_name = 'files'
    filterset_class = FileFilter


def file_listing(request):
    files = File.objects.select_related('directory').all()
    return render(request, 'files/file_listing.html', {'files': files})


    
# Edit file name view
@csrf_exempt
def edit_file(request, file_id):
    file = get_object_or_404(File, pk=file_id)
    if request.method == 'POST':
        file.name = request.POST.get('name')
        file.owner = request.POST.get('owner')  # Update the owner field
        file.url = request.POST.get('url')
        file.save()
        return redirect('files:file_listing')

    return render(request, 'edit_file.html', {'file': file})

def add_pdf_password_view(request):
    output_pdf_filename = None  # Initialize output_pdf_filename to avoid UnboundLocalError

    if request.method == 'POST':
        form = PDFPasswordForm(request.POST, request.FILES)
        if form.is_valid():
            pdf_file = form.cleaned_data['pdf_file']
            password = form.cleaned_data['password']

            # Define paths
            default_path = "D:\\PyWeb\\media\\resources\\pdf"
            input_pdf_path = os.path.join(default_path, pdf_file.name)
            output_pdf_filename = os.path.splitext(pdf_file.name)[0] + "_pwd.pdf"
            output_pdf_path = os.path.join(default_path, output_pdf_filename)

            # Save uploaded PDF to the server
            with open(input_pdf_path, 'wb') as f:
                for chunk in pdf_file.chunks():
                    f.write(chunk)

            # Add password to PDF
            reader = PdfReader(input_pdf_path)
            writer = PdfWriter()
            for page in reader.pages:
                writer.add_page(page)
            writer.encrypt(password)

            # Write password-protected PDF to output file
            with open(output_pdf_path, 'wb') as output_pdf_file:
                writer.write(output_pdf_file)

            # Redirect to the download URL
            return redirect('files:download_pdf', filename=output_pdf_filename)

    else:
        form = PDFPasswordForm()

    return render(request, 'files/add_pdf_password.html', {
        'form': form,
        'output_pdf_filename': output_pdf_filename  # Now safely includes output_pdf_filename in the context
    })
    
    
def download_pdf_view(request, filename):
    file_path = os.path.join("D:\\PyWeb\\media\\resources\\pdf", filename)
    if os.path.exists(file_path):
        with open(file_path, 'rb') as f:
            response = HttpResponse(f.read(), content_type="application/pdf")
            response['Content-Disposition'] = f'attachment; filename="{filename}"'
            return response
    return HttpResponse("File not found", status=404)

def add_watermark_view(request):
    output_pdf_filename = None  # Initialize to avoid UnboundLocalError

    if request.method == 'POST':
        form = PDFWatermarkForm(request.POST, request.FILES)
        if form.is_valid():
            pdf_file = form.cleaned_data['pdf_file']
            watermark_text = form.cleaned_data['watermark_text']

            # Define paths
            default_path = "D:\\PyWeb\\media\\resources\\pdf"
            input_pdf_path = os.path.join(default_path, pdf_file.name)
            output_pdf_filename = os.path.splitext(pdf_file.name)[0] + "_watermarked.pdf"
            output_pdf_path = os.path.join(default_path, output_pdf_filename)

            # Save uploaded PDF to the server
            with open(input_pdf_path, 'wb') as f:
                for chunk in pdf_file.chunks():
                    f.write(chunk)

            # Step 1: Create a temporary watermark PDF with diagonal text
            watermark_pdf = os.path.join(default_path, "temp_watermark.pdf")
            c = canvas.Canvas(watermark_pdf, pagesize=letter)
            c.setFont("Helvetica", 40)
            c.setFillGray(0.5, alpha=0.3)

            # Rotate the canvas to place the text diagonally
            c.saveState()
            c.translate(letter[0] / 2, letter[1] / 2)  # Move the origin to the center of the page
            c.rotate(45)  # Rotate the canvas by 45 degrees
            c.drawString(-100, 0, watermark_text)  # Adjust position as needed
            c.restoreState()

            c.save()

            # Step 2: Merge the watermark with each page of the input PDF
            reader = PdfReader(input_pdf_path)
            watermark = PdfReader(watermark_pdf).pages[0]
            writer = PdfWriter()

            for page in reader.pages:
                page.merge_page(watermark)
                writer.add_page(page)

            # Step 3: Save the watermarked PDF
            with open(output_pdf_path, "wb") as f:
                writer.write(f)

            # Clean up temporary watermark file
            os.remove(watermark_pdf)

            # Redirect to download URL
            return redirect('files:download_pdf', filename=output_pdf_filename)

    else:
        form = PDFWatermarkForm()

    return render(request, 'files/add_watermark.html', {
        'form': form,
        'output_pdf_filename': output_pdf_filename  # Pass filename to context if it exists
    })


def add_texture_view(request):
    if request.method == 'POST':
        form = PDFTextureForm(request.POST, request.FILES)
        if form.is_valid():
            pdf_file = form.cleaned_data['pdf_file']
            texture_image = form.cleaned_data['texture_image']
            opacity = form.cleaned_data['opacity']

files/templates/files/add_pdf_password.html
{% extends 'product/base.html' %}
{% load static %}
{% block content %}

<!-- add_pdf_password.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PDF Password Protection</title>
	
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

	<!-- Include Bootstrap JS and jQuery (if not already included) -->
	<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
	
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

	<style>
		/* Basic form styling */
		form {
			max-width: 600px;
			margin: 0 auto;
			padding: 20px;
			border: 1px solid #ccc;
			border-radius: 8px;
			background-color: #f9f9f9;
		}

		/* Styling for individual form fields */
		.form-group {
			margin-bottom: 20px;
			display: flex;
			flex-direction: column;
		}

		/* Styling the labels */
		.form-group label {
			font-weight: bold;
			margin-bottom: 5px;
		}

		/* Style for file inputs and text inputs */
		input[type="file"], input[type="password"], input[type="text"], textarea {
			padding: 8px;
			margin: 5px 0;
			border: 1px solid #ccc;
			border-radius: 5px;
		}

		/* Button styling */
		button {
			padding: 10px 15px;
			background-color: #007bff;
			color: white;
			border: none;
			border-radius: 5px;
			cursor: pointer;
		}

		button:hover {
			background-color: #0056b3;
		}

			
	</style>




</head>
<body>
   

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
	<h2>Password Protect a PDF</h2>
    <!-- Form Group for PDF File -->
    <div class="form-group">
        <label for="pdf_file">Choose PDF File</label>
        {{ form.pdf_file }}
    </div>

    <!-- Form Group for Password -->
    <div class="form-group">
        <label for="password">Password</label>
        {{ form.password }}
    </div>

    <!-- Form Group for Submit Button -->
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Apply Password</button>
    </div>
</form>

</body>
</html>

{% endblock content %}

files/templates/files/add_texture.html
{% extends 'product/base.html' %}
{% load static %}
{% block content %}

<!-- add_texture.html -->
<head>
    <meta charset="UTF-8">
    <title>Add Texture to PDF</title>
	
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

	<!-- Include Bootstrap JS and jQuery (if not already included) -->
	<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
	
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
		
	
	<style>
	/* Basic form styling */
	form {
		max-width: 600px;
		margin: 0 auto;
		padding: 20px;
		border: 1px solid #ccc;
		border-radius: 8px;
		background-color: #f9f9f9;
	}

	/* Styling for individual form fields */
	.form-group {
		margin-bottom: 20px;
		display: flex;
		flex-direction: column;
	}

	/* Styling the labels */
	.form-group label {
		font-weight: bold;
		margin-bottom: 5px;
	}

	/* Style for file inputs */
	input[type="file"], input[type="number"] {
		padding: 8px;
		margin: 5px 0;
		border: 1px solid #ccc;
		border-radius: 5px;
	}

	/* Button styling */
	button {
		padding: 10px 15px;
		background-color: #007bff;
		color: white;
		border: none;
		border-radius: 5px;
		cursor: pointer;
	}

	button:hover {
		background-color: #0056b3;
	}

	</style>

</head>



<form method="post" enctype="multipart/form-data">
<h1>Add Texture to PDF</h1>
    {% csrf_token %}
    
    <div class="form-group">
        <label for="pdf_file">Choose PDF File</label>
        {{ form.pdf_file }}
    </div>

    <div class="form-group">
        <label for="texture_image">Choose Texture Image</label>
        {{ form.texture_image }}
    </div>

    <div class="form-group">
        <label for="opacity">Opacity</label>
        {{ form.opacity }}
    </div>

    <button type="submit" class="btn btn-primary">Apply Texture and Download PDF</button>
</form>
{% endblock content %}

files/templates/files/file.html
{% load static %}
{% load custom_filters %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Document Manager</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <style>
        .form-row {
            display: flex;
            flex-wrap: wrap;
            align-items: center;
            justify-content: space-between;
            margin-bottom: 20px;
        }
        .form-row .form-group {
            flex: 1;
            margin-bottom: 10px;
        }
        .breadcrumb {
            background-color: #f8f9fa;
            margin-bottom: 20px;
        }
        .btn-file {
            display: block;
            margin-top: 10px;
        }
        img {
            max-width: 100%;
            height: auto;
        }
        .iframe-container {
            position: relative;
            width: 100%;
            padding-bottom: 56.25%; /* Aspect ratio: 16:9 */
            height: 0;
            overflow: hidden;
            margin-bottom: 20px;
        }
        .iframe-container iframe {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            border: 0;
        }
        video {
            max-width: 100%;
            height: auto;
            margin-bottom: 20px;
        }
    </style>
</head>
<body>
    <div class="container">
        <a href="{% url 'employee:home' %}" class="btn btn-outline-secondary btn-sm mb-3">
            <i class="fas fa-arrow-left"></i>
        </a>
        <h1 class="mb-4">
            <a href="{% url 'files:home' %}"><i class="fas fa-home"></i></a>
            {% if current_directory %}
                {% for ancestor in current_directory.get_ancestors %}
                    / <a href="{% url 'files:directory_view' ancestor.pk %}">{{ ancestor.name }}</a>
                {% endfor %}
                / <span>{{ current_directory.name }}</span>
            {% else %}
                / <span>Home</span>
            {% endif %}
        </h1>
        <div class="row">
            <!-- Directories Section -->
            <div class="col-lg-6 col-md-12 mb-4">
                <div class="form-row">
                    <form method="POST" action="{% url 'files:add_directory' %}" class="form-inline w-100">
                        {% csrf_token %}
                        <div class="form-group flex-grow-1 mr-2">
                            <input type="text" name="name" placeholder="Enter new directory name" class="form-control w-100" required>
                            <input type="hidden" name="parent" value="{% if current_directory %}{{ current_directory.pk }}{% else %}0{% endif %}">
                        </div>
                        <button type="submit" class="btn btn-primary">New Directory</button>
                    </form>
                </div>
                <h3>List of Directories</h3>
                <table class="table table-bordered mt-3">
                    <thead>
                        <tr>
                            <th>Directory Name</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for directory in subdirectories %}
                            <tr>
                                <td>
                                    <a href="{% url 'files:directory_view' directory.pk %}" class="btn btn-outline-secondary btn-sm">{{ directory.name }}</a>
                                </td>
                                <td>
                                    <a href="{% url 'files:delete_directory' directory.pk %}" class="btn btn-danger btn-sm">Delete</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>

            <!-- Files Section -->
            <div class="col-lg-6 col-md-12 mb-4">
                <div class="form-row">
                    <form method="POST" enctype="multipart/form-data" action="{% url 'files:add_file' %}" class="form-inline w-100">
                        {% csrf_token %}
                        <div class="form-group flex-grow-1 mr-2">
                            <input type="text" name="name" placeholder="Enter new file name" class="form-control w-100 mb-2" required>
							<input type="text" name="owner" placeholder="Owner of the file" class="form-control w-100 mb-2">
                            <div class="input-group mb-2">
                                <input type="file" name="file" class="form-control-file w-100" id="file-input">
                                <input type="url" name="url" placeholder="Enter file URL" class="form-control w-100 d-none" id="url-input">
                            </div>
                            <input type="hidden" name="directory" value="{{ current_directory_id }}">
                            <button type="submit" class="btn btn-primary btn-file">New File</button>
                        </div>
                        <div class="form-group">
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="file_option" id="option_file" value="file" checked>
                                <label class="form-check-label" for="option_file">
                                    Upload File
                                </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="file_option" id="option_url" value="url">
                                <label class="form-check-label" for="option_url">
                                    Use URL
                                </label>
                            </div>
                        </div>
                    </form>
                </div>
                <h3>List of Files</h3>
                <table class="table table-bordered mt-3">
                    <thead>
                        <tr>
                            <th>File Name</th>
                            <th>Preview/Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for file in files %}
                            <tr>
                                <td>{{ file.name }}</td>
                                <td>
                                    {% if file.url and "docs.google.com/presentation" in file.url %}
                                        <div class="iframe-container">
                                            <iframe src="{{ file.url|replace:'edit,embed' }}&start=false&loop=false&delayms=3000"
                                                    allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true">
                                            </iframe>
                                        </div>
                                    {% elif file.url and file.url|is_image %}
                                        <img src="{{ file.url }}" alt="{{ file.name }}" class="img-thumbnail mb-2">
                                    {% elif file.file and file.file.url and file.file.url|is_image %}
                                        <img src="{{ file.file.url }}" alt="{{ file.name }}" class="img-thumbnail mb-2">
                                    {% elif file.url and file.url|endswith:".mp4" %}
                                        <video controls>
                                            <source src="{{ file.url }}" type="video/mp4">
                                            Your browser does not support the video tag.
                                        </video>
                                    {% elif file.file and file.file.url and file.file.url|endswith:".mp4" %}
                                        <video controls>
                                            <source src="{{ file.file.url }}" type="video/mp4">
                                            Your browser does not support the video tag.
                                        </video>
                                    {% elif file.url %}
                                        <a href="{{ file.url }}" target="_blank" class="btn btn-outline-primary btn-sm">Open</a>
                                    {% elif file.file %}
                                        <a href="{{ file.file.url }}" target="_blank" class="btn btn-outline-primary btn-sm">Open</a>
                                    {% else %}
                                        <span class="text-danger">No file or URL associated</span>
                                    {% endif %}
                                    <a href="{% url 'files:delete_file' file.pk %}" class="btn btn-danger btn-sm">Delete</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.0/js/bootstrap.bundle.min.js"></script>
    <script>
        $(document).ready(function() {
            $('input[name="file_option"]').on('change', function() {
                if ($(this).val() === 'file') {
                    $('#file-input').removeClass('d-none');
                    $('#url-input').addClass('d-none');
                } else {
                    $('#file-input').addClass('d-none');
                    $('#url-input').removeClass('d-none');
                }
            });
        });
    </script>
</body>
</html>